[WiP!] : Registering Nitrogen and Carbon abundances
SWIFTSIM/SOAP pull request #45
Opened 2023-11-05 20:21 UTC by correac

Adding the calculation of carbon and nitrogen gas abundances in the calculation of SOAP. 
This PR also includes a few suggestions in kinematic_properties.py due to error messages when running SOAP with unyt 3.0.1.

2023-11-09 11:32 UTC, robjmcgibbon requested changes
Looks good, could you please copy the change from https://github.com/SWIFTSIM/SOAP/pull/47/ to fix kinematic_properties

2023-11-29 12:36 UTC, correac commented
@robjmcgibbon As I see it I cannot add the changes from #47 into this branch (Registering Nitrogen). This branch was checkout out from SOAP/Colibre, because the changes I propose are intended to go to SOAP/Colibre and not SOAP/Main. 
#47 was a merge request to SOAP/Main. Adding the changes from SOAP/Master into SOAP/Colibre via my current merge request is not trivial since #47 proposes changes in files that are not in SOAP/Colibre. Does this make sense?

2023-12-05 13:11 UTC, correac commented
@robjmcgibbon Hi Rob, I am happy with the changes in this pull request. Let me know about the changes you suggested. Otherwise, great if this can be merged.

2023-12-08 15:43 UTC, robjmcgibbon reviewed
Looks good, apart from a minor query over the limits you're using

2023-12-08 15:43 UTC, robjmcgibbon commented on aperture_properties.py
> +                self.snapshot_datasets.get_defined_constant("N_O_sun") * 1.0e-5,
Should this be 1.0e-4?

2023-12-08 15:43 UTC, robjmcgibbon commented on aperture_properties.py
> +                self.snapshot_datasets.get_defined_constant("N_O_sun") * 1.0e-5,
Should this be 1.0e-4?

2023-12-15 15:41 UTC, correac commented on aperture_properties.py
> +                self.snapshot_datasets.get_defined_constant("N_O_sun") * 1.0e-5,
Oh! Yes, this should be 1e-4. Fixed!

2023-12-15 15:41 UTC, correac commented on aperture_properties.py
> +                self.snapshot_datasets.get_defined_constant("N_O_sun") * 1.0e-5,
Indeed!

2023-12-15 15:42 UTC, correac commented on aperture_properties.py
> +                self.snapshot_datasets.get_defined_constant("N_O_sun") * 1.0e-5,
New version, now fixed.

2023-12-21 12:18 UTC, merged